server:
  port: 8083

spring:
  application:
    name: notification-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url : jdbc:postgresql://localhost:5435/notification-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true