
services:
  postgres-customer:
    image: postgres
    container_name: acme-pay-notification-service
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notification-service
    volumes:
      - "./data/customer/postgres:/var/lib/postgres/data"
    ports:
      - 5435:5432