server:
  port: 8087

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'


#  cloud:
#    gateway:
#      routes:
#        - id: accounts-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/accounts/**
#          filters:
#            - StripPrefix=2
#          filters:
#            - SetPath=/hello


eureka:
  client:
    service-url:
      defaultZone:  ${EUREKA_URI:http://localhost:8761/eureka}
      fetch-registry: 'true'
      register-with-eureka: 'true'

