
services:
  postgres-account:
    image: postgres
    container_name: acme-pay-account-service
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=account-service
    volumes:
      - "./data/accounts/postgres:/var/lib/postgres/data"
    ports:
      - 5433:5432

  redis:
    image: redis:7.2.0-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./data:/data
