server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgressql.Drive
    password: postgres
    username: postgres
    url: jdbc:postgressql://localhost:5433/account-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresSQLDialect