server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
    url : jdbc:postgresql://localhost:5434/customer-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true


    spring:
      jpa:
        hibernate:
          ddl-auto=update: